# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Graph Paper
url: "https://graphpaper.cncoulter.com/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
description: >- # this means to ignore newlines until "baseurl:"
    Graph Paper is a Jekyll template that incorporates Bootstrap. It's an easy and quick way to have a Jekyll website/blog with the Bootstrap grid already set up. Like graph paper, this provides you with a flexible grid for you to build off of.
locale: en_US
timezone: America/Los_Angeles
author: Cameron N. Coulter
email: cam@cncoulter.com

twitter: # Used for Twitter Cards
  username: camncoulter # Twitter username for the website/publication
  card: summary # "summary" or "summary_large_image"

default_meta_image: /img/notepad-593363_1920.jpg # This is the default image used for Twitter Cards
default_meta_image_alt: "graph paper and a pen"

twitter_username: jekyllrb
github_username:  jekyll

# Google Analytics
# google_analytics: UA-XXXXXXXX-X

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Build settings
permalink: /:year/:month/:day/:title/
markdown: kramdown
sass:
  sass_dir: css
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
